name: test
on: [push]

jobs:
  io_test:
    name: Use Linux Commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Permission Setting
        run: chmod +x script.sh test.sh

      - name: Test run
        run: ./test.sh
